import { Property, Project, SiteSettings, PaymentSettings, Agent } from '../types';

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: 'global',
  siteName: 'AURA LUXURY REAL ESTATE',
  logoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=100&auto=format&fit=crop&q=80',
  faviconUrl: '',
  hotline: '0988 888 999',
  email: 'concierge@auraluxury.vn',
  address: 'Tầng 48, Bitexco Financial Tower, Số 2 Hải Triều, Bến Nghé, Quận 1, TP. Hồ Chí Minh',
  facebookUrl: 'https://facebook.com',
  youtubeUrl: 'https://youtube.com',
  zaloUrl: 'https://zalo.me',
  hero: {
    eyebrow: 'BẤT ĐỘNG SẢN ĐẲNG CẤP & THƯỢNG LƯU',
    heading: 'Kiến Tạo Chuẩn Sống\nXứng Tầm Vị Thế',
    description: 'Khám phá bộ sưu tập bất động sản thượng lưu được tuyển chọn độc quyền tại những vị trí đắc địa nhất Việt Nam.',
    backgroundImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&auto=format&fit=crop&q=85',
    primaryCTA: 'Khám phá bất động sản',
    secondaryCTA: 'Nhận tư vấn riêng',
  },
  stats: {
    properties: 180,
    customers: 2450,
    projects: 35,
    yearsExperience: 15,
  },
  footerDescription: 'AURA Luxury Real Estate là đơn vị tiên phong phân phối và tư vấn chuyển nhượng bất động sản triệu đô, phục vụ cộng đồng tinh hoa với dịch vụ bảo mật và chuẩn mực quốc tế.',
  seo: {
    defaultTitle: 'AURA LUXURY | Bất Động Sản Thượng Lưu Hàng Đầu',
    defaultDescription: 'Sở hữu biệt thự ven sông, Penthouse Thủ Thiêm, Dinh thự nghỉ dưỡng cùng dịch vụ cố vấn đặc quyền AURA.',
    defaultOgImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
  },
  analytics: {
    googleAnalyticsId: 'G-AURALUXURY99',
  },
  updatedAt: new Date().toISOString(),
};

export const INITIAL_PAYMENT_SETTINGS: PaymentSettings = {
  id: 'main',
  bankName: 'Techcombank (Ngân hàng Kỹ thương Việt Nam)',
  bankCode: 'TCB',
  accountName: 'AURA LUXURY REAL ESTATE VIETNAM',
  accountNumber: '19038899888888',
  branch: 'Chi nhánh Sài Gòn - Hội Sở Private Banking',
  qrTemplateUrl: 'https://api.vietqr.io/image/970407-19038899888888-compact2.jpg',
  paymentInstructions: 'Vui lòng ghi chính xác nội dung chuyển khoản được cung cấp để hệ thống đối soát tự động và khoá giữ chỗ tức thì.',
  reservationDepositDefault: 100000000, // 100 triệu
  reservationExpiryMinutes: 1440, // 24 giờ
  updatedAt: new Date().toISOString(),
};

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    name: 'Victoria Hoàng Anh',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    phone: '0988 888 999',
    email: 'hoanganh@auraluxury.vn',
    position: 'Giám Đốc Quản Lý Danh Mục Luxury',
    bio: '12 năm kinh nghiệm tư vấn bất động sản triệu đô tại Thảo Điền, Thủ Thiêm và phân khúc Private Client.',
    facebook: 'https://facebook.com',
    zalo: 'https://zalo.me',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agent-2',
    name: 'Alexander Trần',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    phone: '0977 777 666',
    email: 'alex.tran@auraluxury.vn',
    position: 'Chuyên Gia Cố Vấn Dinh Thự & Penthouse',
    bio: 'Chuyên gia thẩm định pháp lý và cấu trúc giao dịch bảo mật cho các nhà đầu tư chiến lược.',
    facebook: 'https://facebook.com',
    zalo: 'https://zalo.me',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-grand-marina',
    name: 'Grand Marina Saigon',
    slug: 'grand-marina-saigon',
    developer: 'Masterise Homes & Marriott International',
    projectType: 'Căn hộ Hàng hiệu & Penthouse Bến Nghé',
    status: 'selling',
    address: 'Số 2 Tôn Đức Thắng, Phường Bến Nghé, Quận 1',
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 1',
    description: 'Khu bất động sản hàng hiệu Marriott lớn nhất thế giới, tọa lạc tại vị trí độc tôn ven sông Sài Gòn với bến du thuyền riêng và dịch vụ 5 sao toàn cầu.',
    thumbnail: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1600&auto=format&fit=crop&q=85',
    ],
    latitude: 10.7818,
    longitude: 106.7082,
    totalUnits: 4200,
    availableUnits: 18,
    minPrice: 28000000000,
    maxPrice: 165000000000,
    amenities: ['Bến du thuyền quốc tế', 'Dịch vụ quản gia Marriott 24/7', 'Hồ bơi vô cực ngắm pháo hoa', 'Private Club & Cigar Lounge'],
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    seo: {
      title: 'Grand Marina Saigon | Bất Động Sản Hàng Hiệu Marriott Quận 1',
      description: 'Căn hộ và Penthouse hàng hiệu Marriott lớn nhất thế giới ven sông Sài Gòn.',
      keywords: 'Grand Marina Saigon, Marriott Residences, BĐS hàng hiệu Quận 1',
      ogImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'proj-the-river',
    name: 'The River Thủ Thiêm',
    slug: 'the-river-thu-thiem',
    developer: 'Refico & City Garden',
    projectType: 'Khu Căn Hộ & Penthouse Ven Sông',
    status: 'completed',
    address: 'Đại lộ Vòng Cung, Khu đô thị mới Thủ Thiêm',
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 2 (TP. Thủ Đức)',
    description: 'Tuyệt tác kiến trúc ven sông Thủ Thiêm với công viên cảnh quan 4ha, thang máy riêng từng căn và tầm nhìn trực diện skyline trung tâm Quận 1.',
    thumbnail: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&auto=format&fit=crop&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1600&auto=format&fit=crop&q=85',
    ],
    latitude: 10.7835,
    longitude: 106.7198,
    totalUnits: 525,
    availableUnits: 6,
    minPrice: 32000000000,
    maxPrice: 120000000000,
    amenities: ['Thang máy riêng', 'Hồ bơi 50m chuẩn Olympic', 'Rạp chiếu phim ngoài trời', 'Phòng Gym & Yoga view sông'],
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    seo: {
      title: 'The River Thủ Thiêm | Căn Hộ Nghỉ Dưỡng Thượng Lưu Ven Sông',
      description: 'Sở hữu căn hộ và sky villa độc bản tại trung tâm bán đảo Thủ Thiêm.',
      keywords: 'The River Thủ Thiêm, Sky Villa Thủ Thiêm, Căn hộ cao cấp Quận 2',
      ogImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'proj-holm-residences',
    name: 'Holm Residences Thảo Điền',
    slug: 'holm-residences-thao-dien',
    developer: 'Sapphire Vietnam',
    projectType: 'Khu Biệt Thự Biệt Lập Ven Sông',
    status: 'completed',
    address: '145 Nguyễn Văn Hưởng, Phường Thảo Điền',
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 2 (TP. Thủ Đức)',
    description: 'Khu biệt thự ven sông khép kín đẳng cấp bậc nhất Sài Gòn với chỉ 29 căn villa độc bản, bến du thuyền riêng và an ninh bảo vệ chuẩn nguyên thủ.',
    thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
    gallery: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=85',
    ],
    latitude: 10.8067,
    longitude: 106.7321,
    totalUnits: 29,
    availableUnits: 2,
    minPrice: 150000000000,
    maxPrice: 280000000000,
    amenities: ['Bến du thuyền riêng', 'Sân tennis riêng tư', 'Bảo vệ vũ trang 24/7', 'Hồ bơi tràn ven sông'],
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    seo: {
      title: 'Holm Residences Thảo Điền | Biệt Thự Ven Sông Giới Thượng Lưu',
      description: 'Khu biệt thự khép kín ven sông Sài Gòn đẹp nhất Thảo Điền.',
      keywords: 'Holm Thao Dien, Biệt thự Thảo Điền ven sông, Holm Residences',
      ogImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
    },
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-holm-riverside-villa',
    title: 'Dinh Thự Ven Sông Holm Residences Thảo Điền Có Bến Du Thuyền Riêng',
    slug: 'dinh-thu-ven-song-holm-residences-thao-dien',
    propertyCode: 'LUX-880192',
    listingType: 'sale',
    propertyType: 'villa',
    status: 'available',
    shortDescription: 'Dinh thự ven sông biệt lập 850m² tại Holm Thảo Điền với sân vườn rộng, hồ bơi vô cực và bến du thuyền cập bến riêng.',
    description: `Tọa lạc tại vị trí đắc địa nhất trong khuôn viên 29 biệt thự khép kín Holm Residences Thảo Điền, căn dinh thự sở hữu mặt tiền sông Sài Gòn trải dài hơn 30 mét.

Thiết kế hiện đại mang âm hưởng Tropical Modernism do SCDA Singapore chấp bút, tối ưu hóa không gian kính tràn viền để đón trọn gió sông và ánh hoàng hôn rực rỡ.

Nội thất được bài trí tinh xảo từ các thương hiệu hàng đầu thế giới: Poliform, B&B Italia, thiết bị bếp Gaggenau và hệ thống điều hòa lọc không khí âm trần thông minh. 

Khu vực garage ngầm chứa được 4 siêu xe và trang bị phòng chiếu phim gia đình 4K Dolby Atmos riêng biệt.`,
    price: 245000000000, // 245 tỷ
    priceUnit: 'VND',
    area: 850,
    bedrooms: 6,
    bathrooms: 8,
    floors: 3,
    parkingSlots: 4,
    direction: 'Đông Nam',
    projectId: 'proj-holm-residences',
    categoryId: 'cat-villa',
    agentId: 'agent-1',
    address: '145 Nguyễn Văn Hưởng, Phường Thảo Điền, TP. Thủ Đức',
    location: {
      province: 'TP. Hồ Chí Minh',
      district: 'Quận 2 (TP. Thủ Đức)',
      ward: 'Phường Thảo Điền',
      latitude: 10.8067,
      longitude: 106.7321,
    },
    amenities: [
      'Hồ bơi vô cực riêng',
      'Sân vườn nhiệt đới',
      'Bến du thuyền riêng',
      'Thang máy kính riêng biệt',
      'Phòng xông hơi & Spa',
      'Phòng chiếu phim 4K gia đình',
      'Hầm rượu vang nhiệt độ chuẩn',
      'Hệ thống Smart Home chuẩn quốc tế',
      'Garage đỗ 4 siêu xe',
      'An ninh đa lớp 24/7 & Concierge VIP',
    ],
    legalStatus: 'Sổ hồng lâu dài chính chủ, sẵn sàng công chứng chuyển nhượng trong ngày.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTourUrl: null,
    featured: true,
    isHot: true,
    isNew: false,
    viewCount: 1420,
    favoriteCount: 88,
    inquiryCount: 14,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    seo: {
      title: 'Dinh Thự Holm Residences Thảo Điền 850m² Ven Sông Bến Du Thuyền',
      description: 'Bán dinh thự ven sông siêu sang tại Holm Thảo Điền 850m², 6 phòng ngủ, hồ bơi và bến du thuyền riêng.',
      keywords: 'biệt thự holm thảo điền, dinh thự ven sông thảo điền, holm residences',
      ogImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'prop-the-river-penthouse-skyvilla',
    title: 'Penthouse Duplex The River Thủ Thiêm View Trực Diện Landmark 81 & Pháo Hoa',
    slug: 'penthouse-duplex-the-river-thu-thiem',
    propertyCode: 'LUX-772914',
    listingType: 'sale',
    propertyType: 'penthouse',
    status: 'available',
    shortDescription: 'Căn Penthouse Duplex 480m² đỉnh cao tại The River Thủ Thiêm với hồ bơi trên mây và thang máy riêng.',
    description: `Biểu tượng sống trên không trung tại lõi tài chính Thủ Thiêm. Căn Penthouse Duplex chiếm trọn 2 tầng cao nhất của tháp Hudson, sở hữu góc nhìn panorama 270 độ ôm trọn sông Sài Gòn, cầu Ba Son và skyline Quận 1 rực rỡ.

Trần cao thông tầng 6.8m kết hợp kính Low-E 3 lớp cách nhiệt cách âm tuyệt đối. Sân thượng riêng trang bị hồ bơi nước mặn vô cực và quầy bar tiệc rượu ngắm pháo hoa lễ tết.

Gia chủ được phục vụ bởi thang máy riêng biệt đi thẳng vào sảnh nhà và 3 suất đậu ô tô định danh tại tầng hầm.`,
    price: 118000000000, // 118 tỷ
    priceUnit: 'VND',
    area: 480,
    bedrooms: 5,
    bathrooms: 6,
    floors: 2,
    parkingSlots: 3,
    direction: 'Tây Nam',
    projectId: 'proj-the-river',
    categoryId: 'cat-penthouse',
    agentId: 'agent-2',
    address: 'Đại lộ Vòng Cung, Phường An Khánh, TP. Thủ Đức',
    location: {
      province: 'TP. Hồ Chí Minh',
      district: 'Quận 2 (TP. Thủ Đức)',
      ward: 'Phường An Khánh',
      latitude: 10.7835,
      longitude: 106.7198,
    },
    amenities: [
      'Hồ bơi vô cực riêng',
      'Thang máy kính riêng biệt',
      'View panorama 360 độ ngắm hoàng hôn',
      'Hầm rượu vang nhiệt độ chuẩn',
      'Phòng xông hơi & Spa',
      'Hệ thống Smart Home chuẩn quốc tế',
      'An ninh đa lớp 24/7 & Concierge VIP',
    ],
    legalStatus: 'Hợp đồng mua bán trực tiếp chủ đầu tư, đủ điều kiện sang tên sở hữu lâu dài.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=85',
    videoUrl: null,
    virtualTourUrl: null,
    featured: true,
    isHot: false,
    isNew: true,
    viewCount: 2310,
    favoriteCount: 124,
    inquiryCount: 22,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    seo: {
      title: 'Penthouse The River Thủ Thiêm 480m² Hồ Bơi Trên Không',
      description: 'Bán căn penthouse duplex The River Thủ Thiêm hồ bơi riêng view pháo hoa Landmark 81.',
      keywords: 'penthouse the river thủ thiêm, sky villa thủ thiêm, penthouse quận 2',
      ogImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'prop-grand-marina-marriott-suite',
    title: 'Căn Hộ Hàng Hiệu Marriott Residences Grand Marina Saigon Tầng Cao',
    slug: 'can-ho-hang-hieu-marriott-grand-marina-saigon',
    propertyCode: 'LUX-339201',
    listingType: 'sale',
    propertyType: 'apartment',
    status: 'available',
    shortDescription: 'Căn hộ 3PN 165m² hoàn thiện full nội thất Ý cao cấp mang thương hiệu Marriott đầu tiên tại Việt Nam.',
    description: `Chuẩn mực sống hàng hiệu quốc tế ngay tại trung tâm Quận 1. Căn hộ thuộc bộ sưu tập Prime Collection của Marriott International với dịch vụ quản gia phục vụ 24/7 theo tiêu chuẩn khách sạn 5 sao toàn cầu.

Không gian sang trọng với sàn đá cẩm thạch Calacatta nhập khẩu từ Ý, thiết bị vệ sinh Gessi dát vàng, thiết bị bếp Miele cao cấp. View trực diện sông Sài Gòn và bến du thuyền quốc tế.`,
    price: 52000000000, // 52 tỷ
    priceUnit: 'VND',
    area: 165,
    bedrooms: 3,
    bathrooms: 3,
    floors: 1,
    parkingSlots: 1,
    direction: 'Đông',
    projectId: 'proj-grand-marina',
    categoryId: 'cat-apartment',
    agentId: 'agent-1',
    address: 'Số 2 Tôn Đức Thắng, Phường Bến Nghé, Quận 1',
    location: {
      province: 'TP. Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      latitude: 10.7818,
      longitude: 106.7082,
    },
    amenities: [
      'Bến du thuyền riêng',
      'Hồ bơi vô cực riêng',
      'An ninh đa lớp 24/7 & Concierge VIP',
      'Phòng tập Gym riêng hiện đại',
      'Hệ thống Smart Home chuẩn quốc tế',
    ],
    legalStatus: 'Sổ hồng sở hữu lâu dài.',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=85',
    videoUrl: null,
    virtualTourUrl: null,
    featured: true,
    isHot: true,
    isNew: false,
    viewCount: 1890,
    favoriteCount: 95,
    inquiryCount: 16,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    seo: {
      title: 'Căn Hộ Hàng Hiệu Marriott Grand Marina Saigon 3PN 165m²',
      description: 'Bán căn hộ hàng hiệu Marriott Grand Marina Saigon Quận 1, 3 phòng ngủ view sông.',
      keywords: 'Grand Marina Saigon, Marriott Residences Quận 1, Căn hộ hạng sang Bến Nghé',
      ogImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'prop-shophouse-dong-khoi-heritage',
    title: 'Shophouse Mặt Tiền Đồng Khởi - Lê Lợi Vị Trí Vàng Trung Tâm Quận 1',
    slug: 'shophouse-dong-khoi-le-loi-quan-1',
    propertyCode: 'LUX-991204',
    listingType: 'rent',
    propertyType: 'shophouse',
    status: 'available',
    shortDescription: 'Cho thuê tòa shophouse thương mại 5 tầng mặt tiền góc Đồng Khởi, phù hợp flagship store thương hiệu xa xỉ.',
    description: `Cơ hội sở hữu vị trí nhận diện thương hiệu hàng đầu Đông Nam Á. Tòa shophouse tọa lạc tại nút giao đắt giá nhất Sài Gòn, liền kề Nhà hát Thành phố và các khách sạn 5 sao danh tiếng.

Diện tích sàn 140m² x 5 tầng (tổng diện tích sử dụng 700m²), trang bị thang máy tốc độ cao, hệ thống PCCC tiêu chuẩn quốc tế và mặt tiền ốp kính cong Panorama siêu sang.`,
    price: 380000000, // 380 triệu / tháng
    priceUnit: 'VND/month',
    area: 700,
    bedrooms: 2,
    bathrooms: 6,
    floors: 5,
    parkingSlots: 2,
    direction: 'Đông Bắc',
    projectId: null,
    categoryId: 'cat-shophouse',
    agentId: 'agent-2',
    address: 'Đường Đồng Khởi, Phường Bến Nghé, Quận 1',
    location: {
      province: 'TP. Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      latitude: 10.7769,
      longitude: 106.7032,
    },
    amenities: [
      'Thang máy kính riêng biệt',
      'Hệ thống Smart Home chuẩn quốc tế',
      'An ninh đa lớp 24/7 & Concierge VIP',
    ],
    legalStatus: 'Hợp đồng thuê dài hạn 5-10 năm, pháp lý công chứng đầy đủ.',
    images: [
      'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200&auto=format&fit=crop&q=85',
    videoUrl: null,
    virtualTourUrl: null,
    featured: true,
    isHot: true,
    isNew: false,
    viewCount: 1650,
    favoriteCount: 72,
    inquiryCount: 19,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    seo: {
      title: 'Cho Thuê Tòa Nhà Shophouse Đồng Khởi Quận 1 - Vị Trí Kim Cương',
      description: 'Cho thuê shophouse mặt tiền Đồng Khởi Quận 1, 700m2 sàn kinh doanh flagship store luxury.',
      keywords: 'thuê shophouse đồng khởi, shophouse quận 1, mặt bằng đồng khởi',
      ogImage: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'prop-ocean-villa-da-nang-heritage',
    title: 'Biệt Thự Đảo Nghỉ Dưỡng Mặt Biển Non Nước Đà Nẵng Đẳng Cấp 5 Sao',
    slug: 'biet-thu-nghi-duong-mat-bien-da-nang',
    propertyCode: 'LUX-445102',
    listingType: 'sale',
    propertyType: 'resort',
    status: 'available',
    shortDescription: 'Dinh thự biển 650m² sở hữu bãi cát trắng riêng tư, hồ bơi tràn bờ nước mặn và tầm nhìn trọn đại dương.',
    description: `Khu nghỉ dưỡng siêu sang tọa lạc tại cung đường di sản Đà Nẵng - Hội An. Dinh thự sở hữu lối đi thẳng ra bãi biển nguyên sơ Non Nước, thiết kế mở giao hòa tuyệt đối cùng thiên nhiên.

Sở hữu 4 phòng ngủ master trang bị bồn tắm sục Jacuzzi ngoài trời, sân tiệc nướng BBQ ven biển và dịch vụ ẩm thực đầu bếp riêng theo yêu cầu.`,
    price: 88000000000, // 88 tỷ
    priceUnit: 'VND',
    area: 650,
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    parkingSlots: 2,
    direction: 'Đông',
    projectId: null,
    categoryId: 'cat-resort',
    agentId: 'agent-1',
    address: 'Đường Trường Sa, Phường Hòa Hải, Quận Ngũ Hành Sơn',
    location: {
      province: 'Đà Nẵng',
      district: 'Ngũ Hành Sơn',
      ward: 'Phường Hòa Hải',
      latitude: 15.9982,
      longitude: 108.2612,
    },
    amenities: [
      'Hồ bơi vô cực riêng',
      'Sân vườn nhiệt đới',
      'Phòng xông hơi & Spa',
      'Khu BBQ ngoài trời ven sông',
      'An ninh đa lớp 24/7 & Concierge VIP',
      'View panorama 360 độ ngắm hoàng hôn',
    ],
    legalStatus: 'Sổ đỏ sở hữu lâu dài cho người Việt Nam.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=85',
    videoUrl: null,
    virtualTourUrl: null,
    featured: true,
    isHot: false,
    isNew: true,
    viewCount: 1140,
    favoriteCount: 68,
    inquiryCount: 9,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    seo: {
      title: 'Biệt Thự Biển Đà Nẵng 650m² Mặt Biển Non Nước Sở Hữu Lâu Dài',
      description: 'Bán biệt thự nghỉ dưỡng mặt biển Đà Nẵng 650m2 có hồ bơi riêng.',
      keywords: 'biệt thự biển đà nẵng, ocean villa đà nẵng, resort ngũ hành sơn',
      ogImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=85',
    },
  },
  {
    id: 'prop-tay-ho-mansion-hanoi',
    title: 'Dinh Thự Đơn Lập Quảng An Tây Hồ View Trọn Mặt Nước Hồ Tây',
    slug: 'dinh-thu-quang-an-tay-ho-ha-noi',
    propertyCode: 'LUX-551982',
    listingType: 'sale',
    propertyType: 'villa',
    status: 'available',
    shortDescription: 'Dinh thự tân cổ điển 520m² tại bán đảo Quảng An Tây Hồ, kiến trúc quý tộc Pháp với hầm rượu và thang máy.',
    description: `Tọa lạc tại khu vực ngoại giao đoàn danh giá nhất thủ đô Hà Nội. Dinh thự sở hữu vị thế phong thủy vượng khí bậc nhất bên bờ Hồ Tây thoáng đãng.

Kiến trúc Tân Cổ Điển Pháp sang trọng, toàn bộ cửa và nội thất được chạm khắc gỗ gõ đỏ quý hiếm, kết hợp đèn chùm pha lê Baccarat nhập khẩu từ Paris.`,
    price: 195000000000, // 195 tỷ
    priceUnit: 'VND',
    area: 520,
    bedrooms: 5,
    bathrooms: 6,
    floors: 4,
    parkingSlots: 3,
    direction: 'Nam',
    projectId: null,
    categoryId: 'cat-villa',
    agentId: 'agent-2',
    address: 'Phố Quảng An, Phường Quảng An, Quận Tây Hồ',
    location: {
      province: 'Hà Nội',
      district: 'Tây Hồ',
      ward: 'Phường Quảng An',
      latitude: 21.0628,
      longitude: 105.8275,
    },
    amenities: [
      'Sân vườn nhiệt đới',
      'Thang máy kính riêng biệt',
      'Hầm rượu vang nhiệt độ chuẩn',
      'Phòng xông hơi & Spa',
      'Garage đỗ 4 siêu xe',
      'An ninh đa lớp 24/7 & Concierge VIP',
    ],
    legalStatus: 'Sổ đỏ lâu dài vuông vắn chính chủ.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=85',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
    videoUrl: null,
    virtualTourUrl: null,
    featured: true,
    isHot: false,
    isNew: false,
    viewCount: 1530,
    favoriteCount: 79,
    inquiryCount: 11,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    seo: {
      title: 'Biệt Thự Quảng An Tây Hồ 520m² View Hồ Tây - Sổ Đỏ Chính Chủ',
      description: 'Bán biệt thự đơn lập Quảng An Tây Hồ Hà Nội 520m2 vị trí đắc địa.',
      keywords: 'biệt thự tây hồ, biệt thự quảng an, nhà đất tây hồ hà nội',
      ogImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=85',
    },
  },
];
